FROM apache/airflow:2.10.5-python3.12
RUN pip install --no-cache-dir \
      "apache-airflow-providers-docker" \
      "mlflow-skinny==2.16.2" \
      "boto3" \
      --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.12.txt"
